SomeMvcApp/Controllers/SomeController.cs
using System;
using System.Data;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net.Http;
using System.Web.Mvc;
using System.Web.Routing;
using PagedList;
using Raven.Client.Embedded;
using SomeMvcApp.Models;
using SomeMvcApp.Models.Repository;

namespace SomeMvcApp.Controllers
{
	public class SomeController : Controller
	{
		private readonly IRepository _repository;

		public SomeController()
		{
			//_repository = new SomeContextRepository(new SomeContext());
			_repository = new SomeDocRepository(new EmbeddableDocumentStore { ConnectionStringName = "RavenEmbedded" });
		}
		
		//
		// GET: /Some/

		public ActionResult Index(string sortOrder, string searchString, string currentFilter, int pageNumber = 1)
		{
			ViewBag.SortParam = sortOrder;

			if (Request.HttpMethod == HttpMethod.Get.ToString())
			{
				searchString = currentFilter;
			}
			else // reset paging with due to new filter
			{
				pageNumber = 1;
			}
			ViewBag.CurrentFilter = searchString;

			const int pageSize = 10;                                 //https://github.com/martijnboland/MvcPaging/issues/15
			return View(_repository.GetItems(sortOrder, searchString).ToList().ToPagedList(pageNumber, pageSize));
		}
		
		//
		// GET: /Some/Details/5

		public ActionResult Details(int id = 0)
		{
			SomeItem someitem = _repository.GetItemById(id);

			if (someitem == null)
			{
				return HttpNotFound();
			}
			return View(someitem);
		}

		//
		// GET: /Some/Create

		public ActionResult Create()
		{
			return View();
		}

		//
		// POST: /Some/Create

		[HttpPost]
		public ActionResult Create(SomeItem someitem)
		{
			try
			{
				if (ModelState.IsValid)
				{
					_repository.InsertItem(someitem, User.Identity.Name);
					_repository.Save();

					return RedirectToAction("Index");
				}
			}
			catch (DataException)
			{
				//Log the error (add a variable name after DataException)
				ModelState.AddModelError("", "Unable to save changes. Try again, please.");
			}

			return View(someitem);
		}

		//
		// GET: /Some/Edit/5/true

		public ActionResult Edit(int id = 0, bool isLocked = false)
		{
			//bool isLocked = Convert.ToBoolean(ViewBag.IsLocked);
			SomeItem someitem = _repository.GetItemById(id);
			
			if (someitem == null)
			{
				return HttpNotFound();
			}
			
			//currently is not locked but needs lock
			if (!someitem.Locked && isLocked)
			{
				SetItemLock(someitem, true);
			}
			//currently is locked but not needs lock
			else if (someitem.Locked && !isLocked)
			{
				SetItemLock(someitem, false);
			}

			return View(someitem);
		}

		private void SetItemLock(SomeItem someitem, bool isLocked)
		{
			try
			{
				someitem.UpdatedBy = _repository.GetItems().First(si => si.Id == someitem.Id).UpdatedBy;
				var currentUser = _repository.GetUserByName(User.Identity.Name);

				if (someitem.UpdatedBy == currentUser || !someitem.Locked)
				{
					someitem.UpdatedBy = currentUser;
					someitem.Locked = isLocked;
					_repository.UpdateItem(someitem);
					_repository.Save();
			}
		}
			catch (InvalidOperationException)
			{
				/*Sequence contains no elements*/
			}
		}

		//
		// POST: /Some/Edit/5

		[HttpPost]
		public ActionResult Edit(SomeItem someitem)
		{
			try
			{
				if (ModelState.IsValid)
				{
					someitem.UpdatedBy = _repository.GetUserByName(User.Identity.Name);
					_repository.UpdateItem(someitem);
					_repository.Save();

					return RedirectToAction("Index");
				}
			}
			catch (DbUpdateConcurrencyException ex)
			{
				var entry = ex.Entries.Single();
				var clientValues = (SomeItem)entry.Entity;
				//_db.Entry(clientValues).Reference(si => si.UpdatedBy).Load();
				_repository.LoadReference(clientValues);
				var databaseValues = (SomeItem)entry.GetDatabaseValues().ToObject();
				databaseValues.UpdatedBy = _repository.GetItems().First(si => si.Id == databaseValues.Id).UpdatedBy; //_db.SomeItems.Include("UpdatedBy").First(si => si.Id == databaseValues.Id).UpdatedBy;
				
				if (databaseValues.Title != clientValues.Title)
				{
					ModelState.AddModelError("Title", "Current value: " + databaseValues.Title);
				}
				
				if (databaseValues.Description != clientValues.Description)
				{
					ModelState.AddModelError("Description", "Current value: " + databaseValues.Description);
				}

				if (databaseValues.UpdatedBy.Name != clientValues.UpdatedBy.Name)
				{
					ModelState.AddModelError("UpdatedBy", "Current value: " + databaseValues.UpdatedBy.Name);
				}
				ModelState.AddModelError(string.Empty, "The record you attempted to edit "
					+ "was modified by another user after you got the original value. The "
					+ "edit operation was canceled and the current values in the database "
					+ "have been displayed. If you still want to edit this record, click "
					+ "the Save button again. Otherwise click the Cancel to return to list of items.");
				someitem.TimeStamp = databaseValues.TimeStamp;

				///////////////////Permanent Save///////////////////
				//var updatedItem = _db.SomeItems.Find(someitem.Id);
				//var currentUser = _db.Users.Single(u => u.Name.ToLower() == User.Identity.Name.ToLower());
				//updatedItem.UpdatedBy = currentUser;
				//// end editing
				//updatedItem.Locked = false;
				//_db.Entry(updatedItem).CurrentValues.SetValues(someitem);
				//_db.SaveChanges();
			}
			catch (DataException)
			{
				//Log the error
				ModelState.AddModelError(string.Empty, "Unable to save changes. Try again.");
			}

			return View(someitem);
		}
		
		[HttpPost]
		public JsonResult JsonSave(SomeItem someItem)
		{
			bool saved = false;
			string message = string.Empty;

			try
			{
				if (ModelState.IsValid)
				{
					someItem.UpdatedBy = _repository.GetUserByName(User.Identity.Name);
					((SomeContextRepository)_repository).StrongUpdateItem(someItem);
					saved = true;
				}
			}
			catch (Exception ex)
			{
				message = ex.Message;
			}

			return Json(Tuple.Create(saved, message)); //Json(someItem, JsonRequestBehavior.AllowGet);
		}

		public void JsonUnlock(SomeItem someItem)
		{
			_repository.UnlockAllUsersItems(User.Identity.Name);
		}

		//
		// GET: /Some/Delete/5

		public ActionResult Delete(int id = 0, bool concurrencyError = false)
		{
			SomeItem someitem = _repository.GetItemById(id);

			if (someitem == null)
			{
				return HttpNotFound();
			}

			if (concurrencyError)
			{
				ViewBag.ConcurrencyErrorMessage = "The record you attempted to delete "
					+ "was modified by another user after you got the original values. "
					+ "The delete operation was canceled and the current values in the "
					+ "database have been displayed. If you still want to delete this "
					+ "record, click the <b>Delete</b> button again. Otherwise "
					+ "click the <b>Back to List</b> hyperlink.";
			}

			return View(someitem);
		}

		//
		// POST: /Some/Delete/5

		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteConfirmed(SomeItem someItem)
		{
			try
			{
				_repository.DeleteItem(someItem);
				_repository.Save();

				return RedirectToAction("Index");
			}
			catch (DbUpdateConcurrencyException)
			{
				return RedirectToAction("Delete", new RouteValueDictionary { {"concurrencyError", true} });
			}
			catch (DataException)
			{
				//Log the error (add a variable name after Exception) 
				ModelState.AddModelError(string.Empty, "Unable to save changes. Try again, and if the problem persists contact your system administrator.");
				return View(someItem);
			} 
		}

		public ActionResult About()
		{
			return View(_repository.GetUsers());
		}

		protected override void Dispose(bool disposing)
		{
			_repository.Dispose();
			base.Dispose(disposing);
		}

	}
}

SomeMvcApp/Views/Some/About.cshtml
@model IEnumerable<SomeMvcApp.Models.User>

@{
	ViewBag.Title = "About";
}

<hgroup class="title">
	<h1>@ViewBag.Title</h1>
	<h2>@ViewBag.Message</h2>
</hgroup>

<article>
<div id="instruction" title="Click to open" style="cursor: help" ><h3>Инструкция</h3></div>
<div id="manual" style="display: none;">
<p>
1. "Из коробки" есть 2 зарегистрированных пользователя (пароль для обоих - "123456"):<br />
- "User1"<br />
- "User2"</p>
<p>
2. После авторизации (Log in) отображается список доступных записей в базе данных</p>
<p>
3. Справа доступны кнопки для манипулирования записями: <br />
- Редактирование (Edit), <br />
- Просмотр деталей (Details)<br />
- Удаление (Delete)</p>
<p>
4. Перед редактированием, предоставляется выбор блокировки (Confirm message) (Пессимистическая - "OK", без блокировки - "Cancel" )</p>
<p>
5. Если запись заблокирована другим пользователем, то редактирование и удаление записи запрещено (присутствует запись о блокировании записи и имя пользователя, кто её заблокировал)</p>
<p>
6. Если запись редактировалась без предварительной блокировки (оптимистическая блокировка), то пользователю, который сохраняет измененную запись последним, предоставляется сообщение, какие поля изменились в базе и их значение в сравнении с текущими значениями, которые внёс текущий пользователь (вы).</p>
<p>
6.1 После отображения конфликтных полей пользователь может:<br />
 - перезаписать изменения в базе своими изменениями - просто нажав кнопку "Save" ещё раз, <br />
 - перезаписать только некоторые поля (взяв предложенные изменения из базы)<br />
 - отменить свои изменения нажав "Cancel" или "Back to list".</p>
</div>
</article>

<aside>
	<h3>Some Aside Title</h3>
	<p>
		Use this area to provide additional information.
	</p>
	<ul>
		<li>@Html.ActionLink("Home", "Index", "Home")</li>
		<li><b>About</b></li>
	</ul>
</aside>

<div style="float:left; width:70%">
	<table style="border: 1px solid; width:100%">
		<tr>
			<th colspan="4" style="text-align:center; border-bottom:1px solid;">
				<h3>User&nbsp;creation&nbsp;Statistics</h3>
			</th>
		</tr>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Created)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.ItemsCreated)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.ItemsUpdated)
			</th>
		</tr>
		@foreach (var item in Model)
		{ 
			<tr>
				<td>
					@item.Name
				</td>
				<td>
					@string.Format("{0:dd.MM.yyyy / H:mm:ss}", item.Created)
				</td>
				<td>
					@item.ItemsCreated.Count
				</td>
				<td>
					@item.ItemsUpdated.Count
				</td>
			</tr>
		}
	</table>
</div>

<script type="text/javascript">
	$('#instruction').click(function () {
		$('#manual').slideToggle('slow', function () {
			$('#instruction').attr("title", function (index, attr) {
				this.title = (this.title == "Click to open") ? "Click to close" : "Click to open";
			});
		});
	});
</script>

SomeMvcApp/Views/Some/Create.cshtml
@model SomeMvcApp.Models.SomeItem

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>SomeItem</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        @*<div class="editor-label">
            @Html.LabelFor(model => model.Locked)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Locked)
            @Html.ValidationMessageFor(model => model.Locked)
        </div>*@

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SomeMvcApp/Views/Some/Delete.cshtml
@model SomeMvcApp.Models.SomeItem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>@(Model.Locked ? "This record is locked! You can not delete it." : "Are you sure you want to delete this?")</h3>
<p class="error">@MvcHtmlString.Create(ViewBag.ConcurrencyErrorMessage)</p> 

<fieldset>
    <legend>SomeItem</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title): 
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>
    @if (!string.IsNullOrWhiteSpace(Model.Description))
    {
        <div class="display-label">
             @Html.DisplayNameFor(model => model.Description): 
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Description)
        </div>
    }
</fieldset>
@using (Html.BeginForm()) {
    @Html.HiddenFor(model => model.Id) 
    @Html.HiddenFor(model => model.TimeStamp) 
    <p>
        <input type="submit" value="Delete" @(Html.Raw(Model.Locked ? "disabled=\"disabled\" style=\"color:Gray\" title=\"Item is locked\"" : string.Empty)) />
        @Html.ActionLink("Back to List", "Index")
    </p>
}

SomeMvcApp/Views/Some/Details.cshtml
@model SomeMvcApp.Models.SomeItem

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div class="display-field">
    <h3>
        @if (Model.Locked)
        {
            <span class="red-style">Record is locked</span> <span>by</span> @Html.DisplayFor(model => model.UpdatedBy.Name)
        }
        else
        {
            <span>Record is not locked</span>
        }
    </h3>
</div>

<fieldset>
    <legend>SomeItem</legend>

    <div class="display-label">
         <h3>@Html.DisplayNameFor(model => model.Title)</h3>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         <h3>@Html.DisplayNameFor(model => model.Description)</h3>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
    
    <div class="display-label">
        <h4>@Html.DisplayNameFor(model => model.CreatedBy)</h4>
    </div>
    <div class="display-field">      
        <strong>User Name:</strong> @Html.DisplayFor(model => model.CreatedBy.Name)
    </div>
    
    <div class="display-label">
         <h4>@Html.DisplayNameFor(model => model.UpdatedBy)</h4>
    </div>
    <div class="display-field">
        <strong>User Name:</strong> @Html.DisplayFor(model => model.UpdatedBy.Name)
        <br />
        <br />
    </div>

    <div class="display-label">
         <strong>TimeStamp:</strong> @Html.DisplayFor(model => model.TimeStamp)
    </div>

</fieldset>
<p>
@if (!Model.Locked)
{
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) @("|")
}
    @Html.ActionLink("Back to List", "Index")
</p>

SomeMvcApp/Views/Some/Edit.cshtml
@model SomeMvcApp.Models.SomeItem
@{
    ViewBag.Title = "Edit";
    ViewBag.SelfLock = false;
    if (Model.Locked)
    {
        ViewBag.SelfLock = User.Identity.Name.ToLower() == Model.UpdatedBy.Name.ToLower();
    }
}
<h2>Edit</h2>
<div id="saveResult" visibility="hidden"></div>
<h3>
    @if (Model.Locked)
    {
        <span class="red-style">Record is locked</span> <span>by</span> 
        if (ViewBag.SelfLock)
        { 
        <span>You</span>
        }
        else
        {
        @Html.DisplayFor(model => model.UpdatedBy.Name)
        }
    }
</h3>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>SomeItem</legend>
        @Html.HiddenFor(model => model.Id)
        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @if (Model.Locked && !ViewBag.SelfLock)
            {
                @Model.Title 
            }
            else
            {
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            }
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @if (Model.Locked && !ViewBag.SelfLock)
            {
                @Model.Description 
            }
            else
            {
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            }
        </div>
        <div class="display-label">
            <h4>@Html.LabelFor(model => model.CreatedBy)</h4>
        </div>
        <div class="display-field">
            <strong>User Name:</strong> @Html.DisplayFor(model => model.CreatedBy.Name)
        </div>
        <div class="display-label">
            <h4>@Html.LabelFor(model => model.UpdatedBy)</h4>
        </div>
        <div class="display-field">
            <strong>User Name:</strong> @Html.DisplayFor(model => model.UpdatedBy.Name)
            @Html.ValidationMessageFor(model => model.UpdatedBy)
        </div>
        <div class="display-field">
            <h3>
                @if (!Model.Locked)
                {
                    @*@Html.EditorFor(model => model.Locked)*@
                    <span id="lockSpan">No lock</span>
                }</h3>
        </div>
        @Html.HiddenFor(model => model.TimeStamp)
        <p>
            @if (!Model.Locked || ViewBag.SelfLock)
            {
                <input type="submit" value="Save" id="submitBtn" /> @("|  ")
            }
            <input type="button" value="Cancel" id="cancelBtn" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index", "Some", null, new { id = "backBtn" }) 
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    //        $('#Locked').change(function () {
    //            var lockText = $(this).attr("checked") ? 'Record is locked' : 'No lock';
    //            $('#lockSpan').text(lockText).toggleClass("red-style");
    //        });

    function redirectToIndex() {
        window.location.href = '/Some/Index';
    };

    function ajaxReturn(event) {
        event.preventDefault();
        if ("@Model.Locked".toLowerCase() == "true") {
            $.ajax({
                url: '@Url.Action("Edit", "Some", new RouteValueDictionary(new { id = Model.Id, isLocked = false }))',
                //data: { id: 'Model.Id' },
                //success: redirectToIndex;
                complete: redirectToIndex
            });
            //redirectToIndex();
        }
        else {
            redirectToIndex();
        }
    };

    $(document).ready(function () {
        $('#submitBtn').click(ajaxSave);

        $('#cancelBtn').click(ajaxReturn);
        $('#backBtn').click(ajaxReturn);
    });

    function ajaxSave(e) {
        var order = {
            Id: $("#Id").val(),
            Title: $("#Title").val(),
            Description: $("#Description").val()
            //UpdatedBy.Name: $("#UpdatedBy.Name").val()
        };

        $.ajax({
            url: "/Some/JsonSave",
            type: "POST",
            data: JSON.stringify(order),
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (result) {
                resultSuccess = result.Item1;
                $("#saveResult").attr("visibility", "visible");
                if (resultSuccess) {
                	saveSuccessfuly("Redirect to main page...");

                    setTimeout(redirectToIndex, 3000);
                } else {
                    saveFailed(result.Item2);
                }
            },
            error: function (e) {
                $("#saveResult").attr("visibility", "visible");
                saveFailed();
            }
        });

        return false;
    };

    function saveSuccessfuly(message) {
    	$("#saveResult").html("Saved successfuly.<br/>" + message);
    	$('#saveResult').toggleClass('red-style', false);
    	$('#saveResult').toggleClass('green-style', true);
    };

    function saveFailed(message){
        $("#saveResult").html("Save failed.<br />" + message);
        $('#saveResult').toggleClass('red-style', true);
        $('#saveResult').toggleClass('green-style', false);
    };
</script>

SomeMvcApp/Views/Some/Index.cshtml
@model PagedList.IPagedList <SomeMvcApp.Models.SomeItem>
       @*IEnumerable < SomeMvcApp.Models.SomeItem >*@

@{
    ViewBag.Title = "Some Items";
}

<h2>Some items</h2>

@using (Html.BeginForm())
{ 
    <p>
        Find by title: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string) &nbsp;
        <input type="submit" value="Search" />
        <input type="button" value="Reset" onclick="resetFilter();"/>
    </p> 
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>

@*Headers*@
<table style="border:2px solid;width:90%;" >
    <tr style="border:1px solid" >
        <th style="border:1px solid;text-align:center;" >
            @*@Html.DisplayNameFor(model => model.Title)*@              @*Title ascending by default*@
            @Html.ActionLink("Title", "Index", new { sortOrder = (string.IsNullOrEmpty(ViewBag.SortParam)) ? "title desc" : string.Empty })
        </th>
        <th style="border:1px solid;text-align:center;" >
            @*@Html.DisplayNameFor(model => model.Description)*@
            @Html.ActionLink("Description", "Index", new { sortOrder = (ViewBag.SortParam == "descript") ? "descript desc" : "descript" })
        </th>
        <th style="border:1px solid;text-align:center;" >
            @*@Html.DisplayNameFor(model => model.CreatedBy)*@
            @Html.ActionLink("Created By", "Index", new { sortOrder = (ViewBag.SortParam == "user") ? "user desc" : "user" })
        </th>
        <th style="border:1px solid;text-align:center;" >
            @Html.DisplayNameFor(model => model[0].UpdatedBy)
        </th>
        <th style="border:1px solid;text-align:center;" >
            @*@Html.DisplayNameFor(model => model.Locked)*@
            @Html.ActionLink("Locked", "Index", new { sortOrder = (ViewBag.SortParam == "lock") ? "lock desc" : "lock" })
        </th>
        <th>
        </th>
    </tr>

@*Rows*@
@foreach (var item in Model)
{
    <tr style="border:1px solid" >
        @Html.HiddenFor(modelItem => item.Id)
        <td style="border:1px solid;text-align:center;" >
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td style="border:1px solid" >
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td style="border:1px solid" >
            @Html.DisplayFor(modelItem => item.CreatedBy.Name)
        </td>
        <td style="border:1px solid" >
            @Html.DisplayFor(modelItem => item.UpdatedBy.Name)
        </td>
        <td style="border:1px solid;text-align:center;" >
            @(item.Locked ? "Yes" : "No")
        </td>
        <td style="border:1px solid;width:auto;" >
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new
       {
           onclick = "return choseLockMode(" + item.Id + ", '" + item.Locked + "', '" + (item.UpdatedBy.Name.ToLower() == User.Identity.Name.ToLower()) + "');"
       }) | 
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}
</table>

@*Paging*@
<div> 
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) 
    of @Model.PageCount 
    &nbsp; 
    @if (Model.HasPreviousPage) 
    { 
        @Html.ActionLink("<<", "Index", new { pageNumber = 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }) 
        @Html.Raw("&nbsp;"); 
        @Html.ActionLink("< Prev", "Index", new { pageNumber = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }) 
    } 
    else 
    { 
        @:<< 
        @Html.Raw("&nbsp;"); 
        @:< Prev 
    } 
    &nbsp; 
    @if (Model.HasNextPage) 
    { 
        @Html.ActionLink("Next >", "Index", new { pageNumber = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }) 
        @Html.Raw("&nbsp;"); 
        @Html.ActionLink(">>", "Index", new { pageNumber = Model.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }) 
    } 
    else 
    { 
        @:Next > 
        @Html.Raw("&nbsp;") 
        @:>> 
    } 
</div>

<script type="text/javascript">
    function resetFilter() {
        window.location = '/Some';
    }
    //$(document).ready(function(){
        function choseLockMode(modId, itemLocked, selfLock) {
            // for now - cannot manage string to bolean convertion in JS :(
            if (itemLocked.toLowerCase() == 'true' && selfLock.toLowerCase() == 'false') return;
        
            if (confirm('Do you want to lock record before editing?')) {
                  //ViewBag.IsLocked = false;
                window.location = '/Some/Edit/' + modId + '/true';
                return false;
            } 
        }
    //});
</script>